pipeline {
    agent any

    stages {

        stage('Generate Files') {
            steps {
                sh 'python3 scripts/onboard.py projects/blog-app.yml'
            }
        }

        stage('Generate Jobs') {
            steps {
                jobDsl(
                    targets: 'jenkins/jobs/*.groovy',
                    removedJobAction: 'IGNORE',
                    removedViewAction: 'IGNORE'
                )
            }
        }

        stage('Run Generated Pipeline') {
            steps {
                build job: 'Blogs/blog_app', wait: false
            }
        }

    }
}